name: "📥 Install dependencies"
description: "Setup node, install pnpm and dependencies"

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "18"
  pnpm-version:
    description: "pnpm version"
    required: false
    default: "7.5.2"
  node-env:
    description: "Node environment"
    required: false
    default: "development"

runs:
  using: "composite"
  steps:
    - name: 📥 Install Node dependencies
      uses: "./github/actions/deps"
      with:
        node-version: ${{ inputs.node-version }}
        pnpm-version: ${{ inputs.pnpm-version }}
        node-env: ${{ inputs.node-env }}
